export enum LoggingEventCategory {
  ai = 'AI',
  sw = 'SW',
  error = 'error',
}

export enum LoggingEvent {
  error = 'error',
  exception = 'exception',
  BackButtonClick = 'back-button-click',
  BackFromRegion = 'back-from-region',
  BackFromCategory = 'back-from-category',
  BackFromSubCategory = 'back-from-sub-category',
  BackFromOffer = 'back-from-offer',
  BackFromHighlights = 'back-from-highlights',
  BackFromSearch = 'back-from-search',
  CategoryClick = 'category-click',
  FooterContactClick = 'footer-contact-click',
  FooterWhatsAppClick = 'footer-whatsapp-click',
  FooterTelegramClick = 'footer-telegram-click',
  MainScreenClick = 'main-screen-button-click',
  NotFoundSheetRows = 'not-found-sheet-rows',
  NotFoundCategory = 'not-found-category',
  NotFoundSubCategory = 'not-found-sub-category',
  NotFoundOffer = 'not-found-offer',
  NotFoundParentQuestion = 'not-found-parent-question',
  NotFoundParentQuestionIsSelf = 'not-found-parent-question-is-self',
  OfferClick = 'offer-click',
  OfferDetailClick = 'offer-detail-click',
  SubCategoryClick = 'sub-category-click',
  SwUpdateActivated = 'sw-update-activated',
  SwUpdateAvailable = 'sw-update-available',
  SwUpdateNotActivated = 'sw-update-not-activated',
  SwUpdateNotAvailable = 'sw-update-not-available',
  ExternalLinkClick = 'external-link',
  QuestionOpen = 'question-open',
  QuestionClose = 'question-close',
}
