// THIS FILE IS GENERATED BY 'npm run set-env-variables'

export const environment = {
  production: true,

  // Configuration/Feature-switches:
  envName: 'test',
  useServiceWorker: false,
  useOffers: true,
  useQandAs: true,
  useQandASearch: true,
  useRegionPerLocale: false,

  // Configuration of content
  appName: 'HIA-test',
  appLogoUrl: '',
  mainPageHeader: 'We test Helpful Information.',
  mainPageIntroduction: 'Select a region:',
  mainPageNotification: '',
  pageAbout: '',
  pagePrivacy: '',
  mainFooter: '',
  errorHeader: 'Error',
  errorMessage: 'Message',
  errorContactUrl: 'https://example.org/contact',
  errorRetry: 'Retest',

  // Regions:
  regions: 'test, ,test-nl,test-ar',
  regionsLabels: 'Test, ,Test NL,Test AR',
  regionsSheetIds:
    'test-sheet-id-1, ,test-sheet-id-2-language-nl,test-sheet-id-3-language-ar',

  // Third-party tokens:
  // Google Sheets API:
  google_sheets_api_key: 'test-api-key',
  google_sheets_api_url: '/data',

  // Application Insights
  appInsightsConnectionString: '',
};
