// THIS FILE IS GENERATED BY 'npm run set-env-variables'

export const environment = {
  production: true,

  // Configuration/Feature-switches:
  envName: 'test',
  useServiceWorker: false,
  useOffers: true,
  useQandAs: true,
  useQandASearch: true,

  // Configuration of content
  appName: 'HIA-test',
  appLogoUrl: '',
  mainPageHeader: 'We test Helpful Information.',
  mainPageIntroduction: 'Select a region:',
  mainPageNotification: '',
  errorHeader: 'Error',
  errorMessage: 'Message',
  errorContactUrl: 'https://example.org/contact',
  errorRetry: 'Retest',

  // Regions:
  regions: 'test',
  regionsLabels: 'Test',
  regionsSheetIds: 'test-id',

  // Third-party tokens:
  // Google Sheets API:
  google_sheets_api_key: 'test-api-key',
  google_sheets_api_url: 'https://example.org/api',

  // Application Insights
  appInsightsConnectionString: '',
};
