# More information on Static Web App workflow configurations,
# See: https://aka.ms/swaworkflowconfig
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'production: Deploy Azure'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '!.github/**'
      - '.github/workflows/deploy-production.yml'
      - '*'
      - '!*.md'
      - 'src/**'

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - '!.github/**'
      - '.github/workflows/deploy-production.yml'
      - '*'
      - '!*.md'
      - 'src/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: 'production'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install
        env:
          HUSKY: 0
        run: 'npm ci --no-fund --no-audit'

      - name: Build
        run: 'npm run build:production'
        env:
          NG_PRODUCTION: 'true'
          ENV_NAME: ''
          NG_USE_SERVICE_WORKER: 'true'
          NG_USE_OFFERS: 'true'
          NG_USE_Q_AND_AS: 'true'
          NG_USE_Q_AND_A_SEARCH: 'true'
          NG_USE_FEEDBACK_PROMPT: 'true'
          TXT_APP_NAME: 'Helpful \n Information'
          TXT_APP_LOGO_URL: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 30"%3E%3Cg fill="%23f5333f"%3E%3Cpath d="M10 0h10v30H10z" /%3E%3Cpath d="M30 10v10H0V10z" /%3E%3C/g%3E%3C/svg%3E'
          TXT_MAIN_PAGE_HEADER: 'Help for undocumented people'
          TXT_MAIN_PAGE_INTRO: >-
            This site is by the Netherlands Red Cross for people who are undocumented: without residence permit or BSN.\n
            We do not share your personal details.\n
            \n
            Find information for local services like legal support, health, and shelter.\n
            Need help or do you have questions? Contact the WhatsApp helpdesk of the Red Cross: [+31 970 10 28 69 64](https://wa.me/3197010286964)\n
            \n
          TXT_MAIN_PAGE_NOTICE: ''
          TXT_PAGE_ABOUT: >-
            ## About \n
            \n
          TXT_PAGE_PRIVACY: >-
            ## Privacy \n
            \n
          TXT_MAIN_FOOTER: >-
            <div class="d-flex d-flex-align-end d-flex-justify-between"><div class="markdown">\n\n
            **Helpful Information**  \n\n
            [About](/about)  \n\n
            [Privacy](/privacy)  \n\n
            [WhatsApp Helpdesk](https://wa.me/3197010286964)  \n\n
            </div><div><a href="https://www.rodekruis.nl/" target=_blank rel="author noopener noreferrer" class="d-flex text-area--level ion-padding"><img src="https://rodekruis.github.io/510-ICON-LIBRARY/Beeldmerk_van_het_Nederlandse_Rode_Kruis.svg" alt="" with=86 height=32 decoding=async loading=lazy></a></div></div>
          TXT_ERROR_HEADER: 'Data Unavailable'
          TXT_ERROR_MESSAGE: 'Reach out to us at: '
          TXT_ERROR_CONTACT_URL: 'https://www.rodekruis.nl/'
          TXT_ERROR_RETRY: 'Try again?'
          REGIONS: >-
            almere,
            amsterdam,
            den-haag,
            eindhoven,
            leeuwarden,
            lelystad,
            nijmegen,
            rotterdam,
            utrecht,
            ,
            ,
            ,
            policy-change-temporary-protection,
          REGIONS_LABELS: >-
            Almere,
            Amsterdam,
            Den Haag,
            Eindhoven,
            Leeuwarden \n(Friesland),
            Lelystad,
            Nijmegen,
            Rotterdam,
            Utrecht,
            ,
            ,
            ,
            Refugees from Ukraine: change in temporary protection,
          REGIONS_SHEET_IDS: >-
            1mod8O9EgvqpCN3ScyAKkOh34x3OGa-8yIc18K_t1xXU,
            1OANMuGJxGBQ2ba3xVfKvTpD0EGQM-ukUrgRyN9tzMbQ,
            1m43Tw7CWRUdPjaStq6dOi9yvHSYInP1lWjLetk1PrTI,
            1OhMLlM6NFD7GkoQEYMP4lnI0FKd__PKdPvYw0x57l8k,
            136iThtEhGoMMVFeuMJZdVSGDKFE6XyCcMWfHRhngGjI,
            1ASaVCURxA7vLmc3Vp5NvoEkR58Mc53R35jTVp7GkxM0,
            1lWUjA8_sqmY7JRmYOBWn3wfRk2whR-2soZ8qfn_Fdaw,
            18qD1PGTK2jTExpVIXXWpjHdpe5KDy7IdcR537CusCLU,
            1ZqizriL_RJ2dCcNVnCj0GM02pqOLWcIF18A4zVigsrU,
            ,
            ,
            ,
            1kt34eFCCVWrC8RAezX9AzYZ0TiQqxGdcF4KCUkHciLY,
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
          GOOGLE_SHEETS_API_URL: 'https://sheets.googleapis.com/v4/spreadsheets'
          AI_CONNECTION_STRING: ${{ secrets.AI_CONNECTION_STRING }}

      - name: Add robots.txt
        run: 'cp src/robots.public.txt www/robots.txt'

      - name: Add Google Site Verification code
        run: 'echo "google-site-verification: google14ff151bbe1f8dd2.html" > www/google14ff151bbe1f8dd2.html'

      - name: Deploy to Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          skip_deploy_on_missing_secrets: true
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_POND_0E01BE103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          config_file_location: '/'
          app_location: 'www'
          output_location: ''
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    environment: 'production'
    steps:
      - name: Close Pull Request for Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_POND_0E01BE103 }}
          action: 'close'
