# More information on Static Web App workflow configurations,
# See: https://aka.ms/swaworkflowconfig
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'production OCW: Deploy Azure'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '!.github/**'
      - '.github/workflows/deploy-production-ocw.yml'
      - '*'
      - '!*.md'
      - 'src/**'

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - '!.github/**'
      - '.github/workflows/deploy-production-ocw.yml'
      - '*'
      - '!*.md'
      - 'src/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: 'production-ocw'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install
        env:
          HUSKY: 0
        run: 'npm ci --omit=optional --no-fund --no-audit'

      - name: Set/override favicon.ico
        run: |
          echo "AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWYe8BCaD/oAqh//8Kof//CqH//wqh//8Kof//CqH/9gmg/98JoP+9CaD/fgmg/wsAAAAAAAAAAAAAAAAAAAAAAAAAAAmg/ywJoP95CaD/lQmg/6UJoP+8CqH/2Qqh/+wKof/4CqH//wqh//8JoP8sAAAAAAAAAAAAAAAAIyPeLSMj3o8jI95NAAAAAAAAAAAAAAAAAAAAABZh7gIWYe4KCaD/FQmg/8sKof//CaD/jgAAAAAAAAAAIyPeCCMj3pkkJN//IyPeqiMj3gsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJoP89CqH//wmh/9wJoP8BAAAAACMj3kUkJN//JCTe/CMj3hT///9A////PQAAAAAAAAAAAAAAAAAAAAAAAAAACJ//CAqh//MKof/8CaD/FyIi3xgjI97uJCTf/yMj3nkjI94B////Uf////7///8jAAAAAAAAAAAAAAAAAAAAAAAAAAAJoP+6CqH//wmg/10jI95oJCTf/yMj3uIjI94RAAAAAJKS7wH////i////zwAAAAAAAAAAAAAAAAAAAAAAAAAACaD/cAqh//8JoP/DIyPesCQk3/8jI95sAAAAAAAAAAAAAAAA////UP////3///8cCqD/Iwmg/zIMoP8SAAAAAAmg/0IKof//CqH/7yQk3/IkJN/4IyPeMQAAAAAjI94NAAAAAP///wb////y////awmg/2sKof/9CaD/wQig/wEJoP9ECqH//wmg/+wkJN/8JCTf/iMj3ikiIt4JIyPe3SMj3s6Rke8R////pf///6kKoP9BCqH//wqh//4JoP96CaD/7gqh//8JoP+nIyPevSQk3/8jI97xIyPesCQk3/8kJN70IyPeHf///0r////FhND/Fgmg/9wKof//CqH//wqh//8JoP/yCaD/NiMj3wkjI9/qJCTf/yQk3/8jI9/+IyPeTwAAAAD///8r////9P///wsJn/8ECaD/ggmg/6wJoP98CaD/LgAAAAAAAAAAIyPfAyMj3lYjI995IyPeHiMj3gIAAAAA////df////7////h////AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP///4v////+/////P///ywAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///90////2////7D///9OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////MP///7L///+Y////VgAAAAAAAAAAAAAAAAAAAAAAAAAA8AcAAPwDAADv8QAAx/kAAM/5AACd+QAAnPwAAD78AAA+zAAAMkgAAANBAACHZwAA/z8AAP4/AAD/PwAA/z8AAA==" | base64 --decode > src/favicon.ocw.ico
          cp --force src/favicon.ocw.ico src/favicon.ico

      - name: Build
        run: 'npm run build:production'
        env:
          NG_PRODUCTION: 'true'
          ENV_NAME: 'V2'
          NG_USE_SERVICE_WORKER: 'true'
          NG_USE_OFFERS: 'false'
          NG_USE_Q_AND_AS: 'true'
          NG_USE_Q_AND_A_SEARCH: 'true'
          TXT_APP_NAME: 'Vragen over Schoolmaaltijden'
          TXT_APP_LOGO_URL: 'https://rodekruis.github.io/510-ICON-LIBRARY/OCWLogo2.svg'
          TXT_MAIN_PAGE_HEADER: ''
          TXT_MAIN_PAGE_INTRO: ''
          TXT_MAIN_PAGE_NOTICE: '<img src="https://schoolmaaltijden.nl/wp-content/uploads/2023/03/NRK_JEF_OCW_Schoolmaaltijden_Primair-768x135.jpg" alt="" loading="async" />'
          TXT_ERROR_HEADER: 'Data Unavailable'
          TXT_ERROR_MESSAGE: 'Reach out to us at: '
          TXT_ERROR_CONTACT_URL: 'https://www.rodekruis.nl/'
          TXT_ERROR_RETRY: 'Try again?'
          REGIONS: >-
            nl,
            en,
            tr,
            ar
          REGIONS_LABELS: >-
            Nederlands,
            English,
            Türkçe,
            العربية
          REGIONS_SHEET_IDS: >-
            1CJsUTqFcglm1mIq6XxI6z67_moGXaFYuGGW_EGUTLuY,
            1SkkLGBnjgfdCZAwtyZN2S5qvo6cxqvljE1JzcQSbf4Y,
            1aOdtxQQ0psavi7QderEd10e1URbCAbGhKNClIG_dUp4,
            1vf5rgteGvxM-ELogXxbBChTqiSk1iMCALhgonmWOTU8
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
          GOOGLE_SHEETS_API_URL: 'https://sheets.googleapis.com/v4/spreadsheets'
          AI_CONNECTION_STRING: ${{ secrets.AI_CONNECTION_STRING }}

      - name: Add robots.txt
        run: 'cp src/robots.public.txt www/robots.txt'

      - name: Add Google Site Verification code
        run: 'echo "google-site-verification: google14ff151bbe1f8dd2.html" > www/google14ff151bbe1f8dd2.html'

      - name: Set ennvironment-specific configuration
        # Prefix existing header-settings with iframe-exception for Twilio Flex:
        run: |
          sed --in-place --expression '/Content-Security-Policy/s/default-src/frame-ancestors https:\/\/flex.twilio.com; default-src/gi' staticwebapp.config.json

      - name: Deploy to Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          skip_deploy_on_missing_secrets: true
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_WATER_02A868203 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          config_file_location: '/'
          app_location: 'www'
          output_location: ''
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    environment: 'production-ocw'
    steps:
      - name: Close Pull Request for Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_WATER_02A868203 }}
          action: 'close'
