# More information on Static Web App workflow configurations,
# See: https://aka.ms/swaworkflowconfig
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'production FAQ: Deploy Azure'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '!.github/**'
      - '.github/workflows/deploy-production-faq.yml'
      - '*'
      - '!*.md'
      - 'src/**'

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - '!.github/**'
      - '.github/workflows/deploy-production-faq.yml'
      - '*'
      - '!*.md'
      - 'src/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: 'production-faq'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install
        env:
          HUSKY: 0
        run: 'npm ci --no-fund --no-audit'

      - name: Set/override favicon.ico
        run: |
          echo "AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAA////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEREREREREREQEREBEBEBARAREQEQEBAREBERAAAQEQEQABEBEBARARAREQEQEBEBEAABEAERABEREREREREREREREREREREREREREiERERERERESIREREREREiIiIRERERESIiIhERERERESIRERERERERIhEREREREREREREREAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" | base64 --decode > src/favicon.env.ico
          cp --force src/favicon.env.ico src/favicon.ico

      - name: Build
        run: 'npm run build:production'
        env:
          NG_PRODUCTION: 'true'
          ENV_NAME: ''
          NG_USE_SERVICE_WORKER: 'true'
          NG_USE_OFFERS: 'false'
          NG_USE_Q_AND_AS: 'true'
          NG_USE_Q_AND_A_SEARCH: 'true'
          TXT_APP_NAME: 'FAQ \n Vraagbaak'
          TXT_APP_LOGO_URL: 'https://rodekruis.github.io/510-ICON-LIBRARY/Beeldmerk_van_het_Nederlandse_Rode_Kruis.svg'
          TXT_MAIN_PAGE_HEADER: 'This web app is made to give helpful information (HIA) about frequently asked questions (FAQ).'
          TXT_MAIN_PAGE_INTRO: 'Please select your FAQ below:'
          TXT_MAIN_PAGE_NOTICE: ''
          TXT_MAIN_ABOUT: >-
            ## About \n
            \n
          TXT_MAIN_PRIVACY: >-
            ## Privacy \n
            \n
          TXT_MAIN_FOOTER: >-
            <div class="d-flex d-flex-align-end d-flex-justify-between"> <div class="markdown">
            **Helpful Information**  \n\n
            [About](/about)  \n\n
            [Privacy](/privacy) \n\n
            [WhatsApp Helpdesk](https://wa.me/3197010286964) \n
            </div> <div> <a href="https://www.rodekruis.nl/" target=_blank rel="author noopener noreferrer" class="d-flex text-area--level ion-padding"><img src="https://rodekruis.github.io/510-ICON-LIBRARY/Beeldmerk_van_het_Nederlandse_Rode_Kruis.svg" alt="" with=86 height=32 decoding=async loading=lazy></a> </div> </div> \n
          TXT_ERROR_HEADER: 'Data Unavailable'
          TXT_ERROR_MESSAGE: 'Reach out to us at: '
          TXT_ERROR_CONTACT_URL: 'https://www.rodekruis.nl/'
          TXT_ERROR_RETRY: 'Try again?'
          REGIONS: >-
            ukraine,
            oekraine,
            shelter,
            opvang,
            ,
            ,
            undocumented-migrants,
            eu-migrants,

          REGIONS_LABELS: >-
            Ukraine (EN),
            Oekraïne (NL),
            Asylum seeker (EN),
            Asielzoeker (NL),
            ,
            ,
            Undocumented Migrants,
            EU Migrants,

          REGIONS_SHEET_IDS: >-
            14NZwDa8DNmH1q2Rxt-ojP9MZhJ-2GlOIyN8RF19iF04,
            1scCAXRoM66dFbR6f2Lj5FwLWZxm3SLbIgt58LeNNeHE,
            15yXp_w0chnFRwIfvY6uRgs7TwzxwuBz9iz-dgDFHsbs,
            1wJ4pfB3l7t16igivt_LkGYmaqZ0hiRsR7_giJUjen-s,
            ,
            ,
            1Veli11xRUzIbmfTF8N57xAZqnMWcH1yKVP63PpfXF7s,
            1SCyJ8v7blSDaeehWuImaRvwXMXC-9o7kbC5bnmotAYw,

          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
          GOOGLE_SHEETS_API_URL: 'https://sheets.googleapis.com/v4/spreadsheets'
          AI_CONNECTION_STRING: ${{ secrets.AI_CONNECTION_STRING }}

      - name: Add robots.txt
        run: 'cp src/robots.public.txt www/robots.txt'

      - name: Add Google Site Verification code
        run: 'echo "google-site-verification: google14ff151bbe1f8dd2.html" > www/google14ff151bbe1f8dd2.html'

      - name: Deploy to Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          skip_deploy_on_missing_secrets: true
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_OCEAN_0BB48C403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          config_file_location: '/'
          app_location: 'www'
          output_location: ''
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    environment: 'production-faq'
    steps:
      - name: Close Pull Request for Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: 's'
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_OCEAN_0BB48C403 }}
          action: 'close'
