# More information on Static Web App workflow configurations,
# See: https://aka.ms/swaworkflowconfig
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'staging FAQ: Deploy Azure'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '!.github/**'
      - '.github/workflows/deploy-staging-faq.yml'
      - '*'
      - '!*.md'
      - 'src/**'

  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - '!.github/**'
      - '.github/workflows/deploy-staging-faq.yml'
      - '*'
      - '!*.md'
      - 'src/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: 'staging-faq'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install
        env:
          HUSKY: 0
        run: 'npm ci --omit=optional --no-fund --no-audit'

      - name: Set/override favicon.ico
        run: 'cp --force src/favicon.gold.ico src/favicon.ico'

      - name: Build
        run: 'npm run build:production'
        env:
          NG_PRODUCTION: 'true'
          ENV_NAME: 'FAQ-Staging'
          NG_USE_SERVICE_WORKER: 'true'
          NG_USE_OFFERS: 'false'
          NG_USE_Q_AND_AS: 'true'
          NG_USE_Q_AND_A_SEARCH: 'true'
          TXT_APP_NAME: 'FAQ / Vraagbaak'
          TXT_APP_LOGO_URL: 'https://rodekruis.github.io/510-ICON-LIBRARY/Beeldmerk_van_het_Nederlandse_Rode_Kruis.svg'
          TXT_MAIN_PAGE_HEADER: 'This web app is made to give helpful information (HIA) about frequently asked questions (FAQ).'
          TXT_MAIN_PAGE_INTRO: >-
            Please select your FAQ below:\n
            \n
            `[ 游릭 = production ]`\n
            `[ 游리 = staging ]`\n
            `[ 游댖 = archive ]`\n
            `[ 游뚾 = development ]`\n
          TXT_ERROR_HEADER: 'Data Unavailable'
          TXT_ERROR_MESSAGE: 'Reach out to us at: '
          TXT_ERROR_CONTACT_URL: 'https://www.rodekruis.nl/'
          TXT_ERROR_RETRY: 'Try again?'
          REGIONS: >-
            ukraine,
            oekraine,
            shelter,
            opvang,
            morocco,
            marokko,
            libya,
            libie,
            ,
            ,
            turkiye-syria,
            turkije-syrie,
            ,
            ,
            jrncs-hotline,
            ,
            example,
            test
          REGIONS_LABELS: >-
            Ukraine (EN) 游릭,
            Oekra칦ne (NL) 游릭,
            Shelter (EN) 游릭,
            Opvang (NL) 游릭,
            Morocco Earthquake (EN) 游릭,
            Marokko Aardbeving (NL) 游릭,
            Libya Floods (EN) 游리,
            Libi칢 Overstromingen (NL) 游리,
            ,
            ,
            T칲rkiye-Syria Earthquake (EN) 游댖,
            Turkije-Syri칢 Aardbeving (NL) 游댖,
            ,
            ,
            JRNCS Hotline 游리,
            ,
            Example/Demo 游리,
            Test/Example 游뚾
          REGIONS_SHEET_IDS: >-
            14NZwDa8DNmH1q2Rxt-ojP9MZhJ-2GlOIyN8RF19iF04,
            1scCAXRoM66dFbR6f2Lj5FwLWZxm3SLbIgt58LeNNeHE,
            15yXp_w0chnFRwIfvY6uRgs7TwzxwuBz9iz-dgDFHsbs,
            1wJ4pfB3l7t16igivt_LkGYmaqZ0hiRsR7_giJUjen-s,
            1LIhuGvtwPVGn4cC7OnbU33cDzkus8O1MfeYLq-YXYsc,
            1oUdEkdpQ4h183nUSj-7rWwXNdAsEopL3m9Iy18dc7LA,
            1N5EAnnc3QVec3M_ME19r1wavzU_4O_R-NPAiiReD9C8,
            1Iy1PaqgP8ugmm4EsZ7GHk4wXFZSm5mUGxml8Dwl4Uso,
            ,
            ,
            1d4vUbvj4KhTj0ZQ_J4RizE3wn0JFjvr9SainTkhyRu8,
            1Rvs49NVJ8iN1Bl-0YUdJwaYF6LqltcC1RovO4UbpV20,
            ,
            ,
            14dv2jpXouk-XjBZpcts32_kth3dun8VZK0KPcGk274s,
            ,
            1l43SgRymj3EPBOd-wp3mWrfcqDZlKbuAy7HQGo8YnT8,
            10SIJdAQSd6loqCyzwK409QS_01Fgp8P4aqoDO8iBvhY
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
          GOOGLE_SHEETS_API_URL: 'https://sheets.googleapis.com/v4/spreadsheets'
          AI_CONNECTION_STRING: ''

      - name: Set/override robots.txt
        run: 'cp src/robots.private.txt www/robots.txt'

      - name: Deploy to Staging
        uses: Azure/static-web-apps-deploy@v1
        with:
          skip_deploy_on_missing_secrets: true
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_ROCK_069A8B403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          config_file_location: '/'
          app_location: 'www'
          output_location: ''
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    environment: 'staging-faq'
    steps:
      - name: Close Pull Request for Staging
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_ROCK_069A8B403 }}
          action: 'close'
