# More information on Static Web App workflow configurations,
# See: https://aka.ms/swaworkflowconfig
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Upgrade (Angular-)Dependencies'

on:
  workflow_dispatch:
  schedule:
    - cron: '20 4 * * SUN'

env:
  WORKFLOW_RUN_URL: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
  WORKFLOW_NEW_PR_URL: '${{ github.server_url }}/${{ github.repository }}/pull/new/auto-upgrade-dependencies'

jobs:
  auto_upgrade_dependencies:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install
        env:
          HUSKY: 0
        run: npm ci --omit=optional --no-fund --no-audit

      - name: Verify environment/tools
        run: |
          node --version
          npm --version
          npx ng version
          npm outdated || true

      - name: Prepare git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -B auto-upgrade-dependencies

      - name: Upgrade dependencies
        run: npx ng update @angular/core @angular/cli @angular-eslint/schematics --create-commits

      - name: Fix syntax
        run: npm run fix:syntax

      - name: Save updated version(s) and create PR
        env:
          HUSKY: 0
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPGRADE_ISSUE_TITLE: 'Upgrade (Angular-)dependencies'
          UPGRADE_ISSUE_BODY: 'By GitHub Action: ${{ env.WORKFLOW_RUN_URL }}'
        run: |
          git add -A || true
          git commit -m "${{ env.UPGRADE_ISSUE_TITLE }} -- ${{ env.UPGRADE_ISSUE_BODY }}" || true
          git push --set-upstream origin auto-upgrade-dependencies --force
          gh issue create --title '${{ env.UPGRADE_ISSUE_TITLE }}' --body '${{ env.UPGRADE_ISSUE_BODY }} -- ${{ env.WORKFLOW_NEW_PR_URL }}' --label 'dependencies'
          echo "Create a new PR with these changes: ${{ env.WORKFLOW_NEW_PR_URL }}" >> $GITHUB_STEP_SUMMARY
